import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${poppins.variable} font-sans antialiased min-h-screen relative bg-transparent text-foreground`}
      >
        {/* Background Gradient */}
        <div
          className="fixed inset-0 -z-20"
          style={{
            background:
              "radial-gradient(125% 125% at 50% 100%, #000000 40%, #fb5d00 100%)",
          }}
        />
        {/* Background Overlay */}
        <div className="fixed inset-0 -z-10 bg-black/50" />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
